#!/usr/bin/env pwsh
# Tests uninstall.ps1 agent-hook removal parity (.5.1): Gemini (generalized
# Remove-DcgHooksFromJsonFile), Cursor (hooks.json + bridge), Copilot (user-level
# field-level), agy/Grok (PreToolUse/Bash shape). Builds the post-install state
# (with a coexisting hook) and asserts dcg is removed while coexisting survives.

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
. (Join-Path $repoRoot 'uninstall.ps1') -LoadFunctionsOnly

$script:failures = 0
function Check([bool]$cond, [string]$msg) {
    if ($cond) { Write-Host "  ok: $msg" } else { Write-Host "  FAIL: $msg" -ForegroundColor Red; $script:failures++ }
}
function New-Tmp { Join-Path ([System.IO.Path]::GetTempPath()) ("dcg_uninst_" + [Guid]::NewGuid().ToString('N')) }
function Test-NoBom([string]$p) {
    $b = [System.IO.File]::ReadAllBytes($p)
    -not ($b.Length -ge 3 -and $b[0] -eq 0xEF -and $b[1] -eq 0xBB -and $b[2] -eq 0xBF)
}
$dcg = "C:\Users\O'Brien\.local\bin\dcg.exe"
$escapedDcg = $dcg.Replace("'", "''")

Write-Host "Test 0: Claude (Bash|PowerShell wrapper) - remove dcg, keep Bash-only hook"
$h0 = New-Tmp; New-Item -ItemType Directory -Path $h0 -Force | Out-Null
try {
    $f = Join-Path $h0 'settings.json'
    @{ hooks = @{ PreToolUse = @(
        @{ matcher = 'Bash|PowerShell'; hooks = @(
            @{ type = 'command'; command = "& '$escapedDcg'"; shell = 'powershell' }) },
        @{ matcher = 'Bash'; hooks = @(
            @{ type = 'command'; command = 'keep-bash-only' }) })
    } } | ConvertTo-Json -Depth 20 | Set-Content $f
    Check ((Remove-DcgHooksFromJsonFile -Path $f) -eq $true) "Claude: returns true (removed)"
    $cfg = Get-Content -Raw $f | ConvertFrom-Json
    $entries = @($cfg.hooks.PreToolUse)
    Check ($entries.Count -eq 1) "Claude: emptied combined matcher pruned"
    Check ($entries[0].matcher -eq 'Bash') "Claude: Bash-only matcher preserved"
    Check ($entries[0].hooks[0].command -eq 'keep-bash-only') "Claude: coexisting command preserved"
} finally { Remove-Item -Recurse -Force $h0 -ErrorAction SilentlyContinue }

Write-Host "Test 1: Gemini (BeforeTool/run_shell_command) - remove dcg, keep coexisting"
$h1 = New-Tmp; New-Item -ItemType Directory -Path (Join-Path $h1 '.gemini') -Force | Out-Null
try {
    $f = Join-Path $h1 '.gemini/settings.json'
    @{ hooks = @{ BeforeTool = @(@{ matcher = 'run_shell_command'; hooks = @(
        @{ command = $dcg; name = 'dcg'; timeout = 5000 }, @{ command = 'other-tool'; name = 'other' }) }) } } |
        ConvertTo-Json -Depth 20 | Set-Content $f
    Check ((Remove-DcgHooksFromJsonFile -Path $f -EventName 'BeforeTool' -DeleteEmptyFile) -eq $true) "returns true (removed)"
    Check (Test-NoBom $f) "rewritten without BOM"
    $cmds = @((Get-Content -Raw $f | ConvertFrom-Json).hooks.BeforeTool[0].hooks | ForEach-Object { $_.command })
    Check (-not ($cmds -contains $dcg)) "dcg removed"
    Check ($cmds -contains 'other-tool') "coexisting hook preserved"
} finally { Remove-Item -Recurse -Force $h1 -ErrorAction SilentlyContinue }

Write-Host "Test 2: Cursor (hooks.json + bridge) - delete bridge, remove entry, keep coexisting"
$h2 = New-Tmp
try {
    $hookDir = Join-Path $h2 '.cursor/hooks'; New-Item -ItemType Directory -Path $hookDir -Force | Out-Null
    $bridge = Join-Path $hookDir 'dcg-pre-shell.ps1'
    Set-Content -Path $bridge -Value '# dcg-cursor-hook: generated by dcg installer'
    $launcher = "powershell -NoProfile -ExecutionPolicy Bypass -File `"$bridge`""
    @{ version = 1; hooks = @{ beforeShellExecution = @(@{ command = $launcher }, @{ command = 'other-tool --x' }) } } |
        ConvertTo-Json -Depth 20 | Set-Content (Join-Path $h2 '.cursor/hooks.json')
    Check ((Unconfigure-CursorHook -HomeDir $h2) -eq $true) "returns true (removed)"
    Check (-not (Test-Path $bridge)) "dcg bridge script deleted"
    $cfg = Get-Content -Raw (Join-Path $h2 '.cursor/hooks.json') | ConvertFrom-Json
    $cmds = @($cfg.hooks.beforeShellExecution | ForEach-Object { $_.command })
    Check (-not ($cmds | Where-Object { $_ -match 'dcg-pre-shell' })) "dcg launcher entry removed"
    Check ($cmds -contains 'other-tool --x') "coexisting hook preserved"
} finally { Remove-Item -Recurse -Force $h2 -ErrorAction SilentlyContinue }

Write-Host "Test 3: Cursor dcg-only file is deleted on clean round-trip"
$h3 = New-Tmp
try {
    $hookDir = Join-Path $h3 '.cursor/hooks'; New-Item -ItemType Directory -Path $hookDir -Force | Out-Null
    $bridge = Join-Path $hookDir 'dcg-pre-shell.ps1'
    Set-Content -Path $bridge -Value '# dcg-cursor-hook: x'
    $launcher = "powershell -NoProfile -ExecutionPolicy Bypass -File `"$bridge`""
    @{ version = 1; hooks = @{ beforeShellExecution = @(@{ command = $launcher }) } } |
        ConvertTo-Json -Depth 20 | Set-Content (Join-Path $h3 '.cursor/hooks.json')
    [void](Unconfigure-CursorHook -HomeDir $h3)
    Check (-not (Test-Path (Join-Path $h3 '.cursor/hooks.json'))) "dcg-only hooks.json deleted (clean round-trip)"
} finally { Remove-Item -Recurse -Force $h3 -ErrorAction SilentlyContinue }

Write-Host "Test 4: Copilot (user-level, field-level) - strip dcg field, keep coexisting"
$r4 = New-Tmp
try {
    $hookDir = Join-Path $r4 'hooks'; New-Item -ItemType Directory -Path $hookDir -Force | Out-Null
    @{ version = 1; hooks = @{ preToolUse = @(
        @{ type = 'command'; bash = $dcg; powershell = $dcg; cwd = '.'; timeoutSec = 30 },
        @{ type = 'command'; bash = $dcg; powershell = 'my-formatter' },   # dcg bash + foreign powershell
        @{ type = 'command'; bash = 'linter'; powershell = 'linter.exe' }) } } |
        ConvertTo-Json -Depth 20 | Set-Content (Join-Path $hookDir 'dcg.json')
    Check ((Unconfigure-CopilotHook -CopilotHome $r4) -eq $true) "returns true (removed)"
    $cfg = Get-Content -Raw (Join-Path $hookDir 'dcg.json') | ConvertFrom-Json
    $entries = @($cfg.hooks.preToolUse)
    Check ($null -eq ($entries | Where-Object { $_.bash -eq $dcg -or $_.powershell -eq $dcg })) "all dcg fields stripped"
    $formatter = @($entries | Where-Object { $_.powershell -eq 'my-formatter' })[0]
    Check (($null -ne $formatter) -and ($null -eq $formatter.PSObject.Properties['bash'])) "entry kept with dcg bash field stripped, foreign powershell retained"
    Check (@($entries | Where-Object { $_.bash -eq 'linter' }).Count -eq 1) "fully-coexisting linter entry intact"
} finally { Remove-Item -Recurse -Force $r4 -ErrorAction SilentlyContinue }

Write-Host "Test 5: agy (~/.gemini/config/hooks.json, PreToolUse/Bash) - remove dcg, keep coexisting"
$h5 = New-Tmp
try {
    $cfgDir = Join-Path $h5 '.gemini/config'; New-Item -ItemType Directory -Path $cfgDir -Force | Out-Null
    $f = Join-Path $cfgDir 'hooks.json'
    @{ hooks = @{ PreToolUse = @(@{ matcher = 'Bash'; hooks = @(
        @{ type = 'command'; command = 'dcg' }, @{ type = 'command'; command = 'keep-me' }) }) } } |
        ConvertTo-Json -Depth 20 | Set-Content $f
    Check ((Remove-DcgHooksFromJsonFile -Path $f -DeleteEmptyFile) -eq $true) "agy: returns true (removed)"
    $cmds = @((Get-Content -Raw $f | ConvertFrom-Json).hooks.PreToolUse[0].hooks | ForEach-Object { $_.command })
    Check (($cmds -notcontains 'dcg') -and ($cmds -contains 'keep-me')) "agy: dcg gone, coexisting kept"
} finally { Remove-Item -Recurse -Force $h5 -ErrorAction SilentlyContinue }

Write-Host "Test 6: dcg-only file is deleted (Codex/agy style, -DeleteEmptyFile)"
$h6 = New-Tmp; New-Item -ItemType Directory -Path $h6 -Force | Out-Null
try {
    $f = Join-Path $h6 'hooks.json'
    @{ hooks = @{ PreToolUse = @(@{ matcher = 'Bash'; hooks = @(@{ type = 'command'; command = 'dcg' }) }) } } |
        ConvertTo-Json -Depth 20 | Set-Content $f
    [void](Remove-DcgHooksFromJsonFile -Path $f -DeleteEmptyFile)
    Check (-not (Test-Path $f)) "dcg-only file deleted"
} finally { Remove-Item -Recurse -Force $h6 -ErrorAction SilentlyContinue }

Write-Host "Test 7: invalid JSON is left unchanged"
$h7 = New-Tmp; New-Item -ItemType Directory -Path $h7 -Force | Out-Null
try {
    $f = Join-Path $h7 'hooks.json'; Set-Content -Path $f -Value '{ not json' -NoNewline
    Check ((Remove-DcgHooksFromJsonFile -Path $f) -eq $false) "invalid JSON -> false (untouched)"
    Check ((Get-Content -Raw $f) -eq '{ not json') "invalid file content unchanged"
} finally { Remove-Item -Recurse -Force $h7 -ErrorAction SilentlyContinue }

Write-Host "Test 8: wrong-matcher dcg hook is removed, sibling survives"
$h8 = New-Tmp; New-Item -ItemType Directory -Path $h8 -Force | Out-Null
try {
    $f = Join-Path $h8 'settings.json'
    @{ hooks = @{ PreToolUse = @(@{ matcher = 'Write'; hooks = @(
        @{ type = 'command'; command = $dcg },
        @{ type = 'command'; command = 'keep-write-hook' }) }) } } |
        ConvertTo-Json -Depth 20 | Set-Content $f
    Check ((Remove-DcgHooksFromJsonFile -Path $f) -eq $true) "wrong-matcher hook: returns true"
    $hooks = @((Get-Content -Raw $f | ConvertFrom-Json).hooks.PreToolUse[0].hooks)
    Check ($hooks.Count -eq 1 -and $hooks[0].command -eq 'keep-write-hook') "wrong-matcher sibling preserved"
} finally { Remove-Item -Recurse -Force $h8 -ErrorAction SilentlyContinue }

Write-Host "Test 9: keep-config and keep-history are independent"
$h9 = New-Tmp
try {
    $config = Join-Path $h9 '.config/dcg'
    $data = Join-Path $h9 '.local/share/dcg'
    New-Item -ItemType Directory -Path $config -Force | Out-Null
    New-Item -ItemType Directory -Path $data -Force | Out-Null
    Set-Content (Join-Path $config 'config.toml') 'mode = "deny"'
    Set-Content (Join-Path $config 'history.db') 'history'
    Set-Content (Join-Path $config 'history.db-wal') 'wal'
    New-Item -ItemType Directory -Path (Join-Path $config 'backups') -Force | Out-Null
    Set-Content (Join-Path $config 'backups/dcg.exe') 'backup'
    Set-Content (Join-Path $data 'blocked.log') 'log'
    Remove-DcgStateDirectories -ConfigDir $config -DataDir $data -KeepHistory
    Check (-not (Test-Path (Join-Path $config 'config.toml'))) "KeepHistory removes config"
    Check (Test-Path (Join-Path $config 'history.db')) "KeepHistory preserves history database"
    Check (Test-Path (Join-Path $config 'history.db-wal')) "KeepHistory preserves SQLite sidecar"
    Check (Test-Path (Join-Path $config 'backups/dcg.exe')) "KeepHistory preserves release backups"
    Check (Test-Path $data) "KeepHistory preserves data directory"

    Set-Content (Join-Path $config 'config.toml') 'mode = "deny"'
    Remove-DcgStateDirectories -ConfigDir $config -DataDir $data -KeepConfig
    Check (Test-Path (Join-Path $config 'config.toml')) "KeepConfig preserves config"
    Check (-not (Test-Path (Join-Path $config 'history.db'))) "KeepConfig removes history database"
    Check (-not (Test-Path (Join-Path $config 'history.db-wal'))) "KeepConfig removes SQLite sidecar"
    Check (-not (Test-Path (Join-Path $config 'backups'))) "KeepConfig removes release backups"
    Check (-not (Test-Path $data)) "KeepConfig removes data directory"
} finally { Remove-Item -Recurse -Force $h9 -ErrorAction SilentlyContinue }

if ($script:failures -gt 0) { Write-Host "$script:failures FAILURE(S)" -ForegroundColor Red; exit 1 }
Write-Host "All uninstall parity tests passed." -ForegroundColor Green
